// Auto-generated by Basic_Audio_Speak (macOS `say` + sox).
// PCM 16-bit signed mono, 16 kHz. Phrases :
//   thomas_biere       [Thomas (fr_FR)    ]  Hmmm, bière...
//   thomas_petitpas    [Thomas (fr_FR)    ]  Un petit pas pour l'homme.
//   thomas_volonte     [Thomas (fr_FR)    ]  Quelle est votre volonté, mon maître ?
//   amelie_knob        [Amélie (fr_CA)    ]  Salut, je suis ton knob.
//   samantha_hasta     [Samantha (en_US)  ]  Hasta la vista, baby.
//   alice_knob         [Alice (it_IT)     ]  Buongiorno, sono il vostro knob.

#pragma once
#include <stdint.h>
#include <stddef.h>

extern const int16_t thomas_biere_pcm[];
extern const size_t  thomas_biere_pcm_len;
extern const int16_t thomas_petitpas_pcm[];
extern const size_t  thomas_petitpas_pcm_len;
extern const int16_t thomas_volonte_pcm[];
extern const size_t  thomas_volonte_pcm_len;
extern const int16_t amelie_knob_pcm[];
extern const size_t  amelie_knob_pcm_len;
extern const int16_t samantha_hasta_pcm[];
extern const size_t  samantha_hasta_pcm_len;
extern const int16_t alice_knob_pcm[];
extern const size_t  alice_knob_pcm_len;
